# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3da8e5c2d5157ab63a01742a31c52d54ccc8b8db46182d8970db46535ef8894d43447c210f04155d85841c6171c130438c881aa4473ef6b8c6d47e4ead0031b2

test:
  secret_key_base: 99982bdffbf8901cc195d1d56b949f524bcffc9dc07193e1ae17b4c7c5f366043d0969a5ebf73d45552ffde3244c28eaf3f72f506fb34cd2f24777845d13df1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
